### ISSUE TITLE
Fixing Home Page Responsiveness and UI (new Look)

### ISSUE THREAD

**Issue by SumitThakur1600** [dipandhali2021/Isekai.io#13]
Enhance the Home Page UI with a fresh, modern design while ensuring seamless responsiveness across all devices. Prioritize user-friendly layouts and smooth navigation.

**Comment by dipandhali2021** [comment]
Hello @SumitThakur1600, go for it. Hope you will come up with a good UI

**Comment by SumitThakur1600** [comment]
I've fixed the issues and I'm considering changing the image to something more visually appealing that better aligns with the project. Should I go ahead and work on this update?

**Comment by dipandhali2021** [comment]
okay go ahead with the update. i am creating a new issue for it.
